### ISSUE TITLE
Smooth lighting causes massive flickering with other mods in Aether.

### ISSUE THREAD

**Issue by awdwyn** [RandomComputerUser/FancyLighting#4]
Using primarily Calamity and Remnants, though with more mods installed, I get a bunch of flickering as soon as I enter the Aether. 

Video showing the issue: [https://youtu.be/tPWj4myDEHo](https://youtu.be/tPWj4myDEHo)

List of enabled mods:
`[
  "AlchemistNPCLite",
  "androLib",
  "Bags",
  "BankButtons",
  "BetterBlending",
  "BossChecklist",
  "BossCursor",
  "CalamityAmmo",
  "CalamityFlamethrowers",
  "CalamityMod",
  "CalamityModMusic",
  "CalamityRarities",
  "CalamityShoes",
  "calamityzeith",
  "CalValEX",
  "CampingMod",
  "CatalystMod",
  "CellphonePylon",
  "Census",
  "ColoredDamageTypes",
  "CraftableAccessories",
  "DialogueTweak",
  "DisableCorruptionSpread",
  "FancyLighting",
  "GhostRespawn",
  "GravityDontFlipScreen",
  "HookStatsAndWingStats",
  "KokoLib",
  "LockBoxesPlus",
  "LookMod",
  "LootBeams",
  "LureBaitDisplay",
  "MagicStorage",
  "MeleeEffects",
  "MoreAccessories",
  "NoFishingQuests",
  "NoPylonRestrictions",
  "PortableWormhole",
  "PotionCharms",
  "RecipeBrowser",
  "RecipeBrowserToMagicStorage",
  "Remnants",
  "SerousCommonLib",
  "ShoeSlot",
  "ShopExpander",
  "ShopQuotesMod",
  "ShorterRespawn",
  "SmarterCursor",
  "SquintlysFurnitureMod",
  "StructureHelper",
  "SummonsUI",
  "Terrarchitect",
  "TrueTooltips",
  "VacuumOreBag",
  "WeaponDisplay",
  "WeaponEnchantments",
  "WheresMyItems",
  "WingSlotExtra",
  "WMITF",
  "WombatQOL"
]`

**Comment by Tyfyter** [comment]
This appears to only trigger with "Enable Smooth Lighting" and "Use Enhanced Shaders and Colors" enabled, and "Light Map Render Mode" set to "Bicubic with Overbright", which is exactly the feature set that enables gamma correction;
Despite this, as far as I can tell it never affects camera mode, and it's almost certainly an issue with setting something into a different state than it was in before given it's unique to shimmer drawing and flashes the shimmer texture, considering this I believe that it is an issue within the [drawing methods in FancyLightingMod.cs](https://github.com/RandomComputerUser/FancyLighting-Terraria/blob/4611c4e2eee5ee4d37b6cc6be6409758f359d654/FancyLightingMod.cs#L344-L1170), likely not setting the render target back to what it should be somewhere.

**Comment by Waffles22-TMod** [comment]
I can second this. Notably, shimmer simply in a pool doesn't cause any issue for me. It's only for I place a shimmer waterfall that the flickering begins.

**Comment by RexBerry** [comment]
> I can second this. Notably, shimmer simply in a pool doesn't cause any issue for me. It's only when I place a shimmer waterfall that the flickering begins.

Seems like shimmer waterfalls are indeed the issue. I wasn't able to replicate this issue until reading your comment. I will attempt to fix this in v0.8.0.

**Comment by Waffles22-TMod** [comment]
In the new version, it definitely occurs less frequently, but it's still happening. My only mods are Fancy Lighting and DragonLens.

Config: 
{
  "UseEnhancedBlurring": true,
  "UseLightMapToneMapping": true,
  "LightMapRenderMode": 2,
  "NormalMapsStrength": 200,
  "FineNormalMaps": true,
  "DoTileEntityAmbientOcclusion": true,
  "AmbientOcclusionRadius": 3,
  "AmbientOcclusionIntensity": 60,
  "AmbientLightProportion": 25,
  "FancyLightingEngineMakeBrighter": true,
  "FancyLightingEngineLightLoss": 10,
  "FancyLightingEngineMode": 4,
  "SimulateGlobalIllumination": true,
  "CustomSkyPreset": 1,
  "UseHiDefFeatures": true,
  "ConfigPreset": 10
}

**Comment by RexBerry** [comment]
> In the new version, it definitely occurs less frequently, but it's still happening. My only mods are Fancy Lighting and DragonLens.
> 
> Config: { "UseEnhancedBlurring": true, "UseLightMapToneMapping": true, "LightMapRenderMode": 2, "NormalMapsStrength": 200, "FineNormalMaps": true, "DoTileEntityAmbientOcclusion": true, "AmbientOcclusionRadius": 3, "AmbientOcclusionIntensity": 60, "AmbientLightProportion": 25, "FancyLightingEngineMakeBrighter": true, "FancyLightingEngineLightLoss": 10, "FancyLightingEngineMode": 4, "SimulateGlobalIllumination": true, "CustomSkyPreset": 1, "UseHiDefFeatures": true, "ConfigPreset": 10 }

I believe you are still on v0.7.x, since there should be two config files in v0.8.x, and the ConfigPreset property was renamed to QualityPreset. If you still experience this issue in the latest version, providing a world file would help me reproduce and fix the issue. I tried reproducing the issues with the mods and settings you've listed, but couldn't.

**Comment by Waffles22-TMod** [comment]
Thank you. The newest version isn't showing up on the modloader for me, so I hadn't realized I wasn't updated.
